title: "Aladino Digitale"
description: "AI generativa per immagini, video e codice – usata sul campo."
url: "https://aladinodigitale.it"
baseurl: "" # lascia vuoto se usi dominio root
repository: "aladinodigitale/aladinodigitale.github.io"

# Autore
author:
  name: "Aladino Digitale"
  avatar: "/assets/images/avatar.png"
  bio: "Esperimenti pratici con l'AI generativa: immagini, video, codice."
  location: "Italia"
  email: "alessio@aladinodigitale.it"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/aladinodigitale"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/company/aladinodigitale"

# Tema
theme: "mmistakes/minimal-mistakes@4.24.0"
locale: "it-IT"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

# Google Fonts (opzionale)
google_fonts:
  - "Fira Code:400,700"
  - "Inter:400,700"

# Navigazione
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: false

# Social sharing
twitter:
  username: aladinodigitale

# Commenti (se vuoi usare disqus più avanti)
# disqus:
#   shortname: tuo-disqus-id

# SEO
seo:
  name: "Aladino Digitale"
  type: "Person"
  description: "Esperimenti e progetti reali con l’intelligenza artificiale generativa."
  social:
    name: "Aladino Digitale"
    links:
      - "https://github.com/aladinodigitale"

